import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const en = {
  brandTitle: 'Health support,', brandTitleAccent: 'close to home.', brandDescription: 'Simple medicine care for you. Quiet confidence for the people who love you.', privacyNote: 'Private, family-only health updates', pillVoice: 'Voice-friendly', pillCare: 'Caregiver loop', pillBilingual: 'English + हिन्दी',
  welcomeLabel: 'Welcome back', newAccountLabel: 'Get started', welcomeBack: 'Welcome back', createAccount: 'Create your account', signInSubtitle: 'Sign in to your health companion.', accountSubtitle: 'Choose how you will use HealthMitra.', chooseRole: 'Choose a role', patient: 'Patient', caregiver: 'Caregiver', name: 'Your name', namePlaceholder: 'Full name', phone: 'Phone number', email: 'Email address', password: 'Password', pleaseWait: 'Please wait…', signIn: 'Sign in', tryDemo: 'Try the demo', patientDemo: 'Patient: Meera', caregiverDemo: 'Caregiver: Arjun', newToHealthMitra: 'New to HealthMitra?', alreadyAccount: 'Already have an account?', prototypeNote: 'Academic prototype · Demo data only',
  patientMode: 'Patient mode', caregiverMode: 'Caregiver mode', mainNavigation: 'Main navigation', language: 'Language', logout: 'Log out', greeting: 'Good morning', watching: 'Watching', sos: 'Emergency SOS', noLinkedPatients: 'No linked patients yet.', loadingPlan: 'Loading your health plan…', joinWithCode: 'Join with code', dismiss: 'Dismiss',
  voiceUnsupported: 'Voice recognition is not supported by this browser.', voiceTryAgain: 'I could not hear that. Please try again.', listening: 'Listening…', voiceUnclear: 'I could not understand a yes or no response.', today: "Today's medicines", medications: 'Medicines', symptoms: 'Symptoms', contacts: 'Contacts', dashboard: 'Dashboard', history: 'History', alerts: 'Alerts', patientToday: 'Your routine', reassurance: 'You are doing great. One step at a time.', allCaughtUp: 'All caught up for today!', dosesComplete: '{{taken}} of {{total}} doses complete', tapAfterTaking: 'Tap a medicine after you take it.', complete: 'complete', missedDoseTitle: 'A dose needs attention', missedDoseBody: 'A caregiver has been notified so they can check in.', noMeds: 'No medicines scheduled', needHelp: 'Need urgent help?', sosDescription: 'Alert connected caregivers and share location.', addMedicine: 'Add medicine', keepScheduleCurrent: 'Keep the schedule current.', consistencyTipTitle: 'A little consistency goes a long way.', consistencyTipBody: 'Taking medicines at the same time each day helps build a healthy routine.', medication: 'Medication', sayIt: 'Say it', taken: 'Taken', skipped: 'Skipped', missed: 'Missed', pending: 'Pending', voice: 'voice',
  caregiverView: 'Caregiver view', dashboardSubtitle: 'A calm, clear view of your loved one’s routine.', linkedPatients: 'Linked patients', selectPatient: 'Select a patient to view their plan.', todayAdherence: 'today adherence', yourLovedOne: 'YOUR LOVED ONE', needsAttention: 'Needs attention', doingWell: 'Doing well today', dayStreak: 'day streak', todaysAdherence: "Today's adherence", dosesTaken: 'Doses taken', openAlerts: 'Open alerts', weeklyAdherence: 'Weekly adherence', weeklySubtitle: 'A simple view of the last 7 days.', todaysSchedule: "Today's schedule", liveSchedule: 'Live status from the patient plan.',
  medicineSchedule: 'Medicine schedule', scheduleSubtitle: 'Keep every prescription in one simple place.', timesDaily: 'time(s) daily', ongoing: 'ongoing', readOnlySchedule: 'You have view-only access to this schedule.', edit: 'Edit', remove: 'Remove', removeMedicineConfirm: 'Remove {{name}} from the schedule?', medicineRemoved: 'Medicine removed.', noHistory: 'No dose history yet.', medicationHistory: 'Medication history', historySubtitle: 'Latest dose responses for {{name}}.',
  careUpdates: 'Care updates', alertsSubtitle: 'Medication and emergency events.', emergencySos: 'Emergency SOS', healthMitra: 'HealthMitra', markRead: 'Mark read', noAlerts: 'You have no alerts.', sosHistory: 'SOS history', sosHistorySubtitle: 'Review and close the loop on emergency events.', locationShared: 'location shared', locationUnavailable: 'location unavailable', openMap: 'Open map', acknowledge: 'Acknowledge', resolve: 'Resolve', sosUpdated: 'SOS status updated.', noSos: 'No SOS events recorded.', active: 'Active', acknowledged: 'Acknowledged', resolved: 'Resolved',
  patientTool: 'Patient tools', feelingQuestion: 'How are you feeling?', symptomSubtitle: 'For minor common symptoms only. This is never a diagnosis.', selectSymptom: 'Select a symptom', speak: 'Speak', severeCheck: 'Symptoms are severe, sudden, or getting worse', safeGuidance: 'See safe guidance', gentleSuggestion: 'Gentle self-care suggestion', seekMedicalGuidance: 'Please seek medical guidance', safetyFirst: 'Safety first', persistentDisclaimer: 'This is not medical advice. Consult a doctor if symptoms persist or worsen.', symptomHeard: 'I heard {{symptom}}.', symptomUnclear: 'Please choose a symptom from the list or try speaking again.', headache: 'Headache', 'mild fever': 'Mild fever', 'common cold': 'Common cold', 'mild body ache': 'Mild body ache', 'mild cough': 'Mild cough',
  helpfulContacts: 'Helpful contacts', contactsSubtitle: 'Doctors and pharmacies your family trusts.', linkCaregiver: 'Link caregiver', linkCaregiverTitle: 'Link a caregiver', linkCaregiverBody: 'Enter the email for an existing caregiver account. You can choose whether they can only view or also edit your schedule.', caregiverEmail: 'Caregiver email', permission: 'Permission', viewOnly: 'View only', canEdit: 'Can edit schedule', caregiverLinked: 'Caregiver linked.', inviteCodeLabel: 'Invite code', addContact: 'Add contact', doctors: 'Doctors', pharmacies: 'Pharmacies', detailsNotAdded: 'Details not added', noContacts: 'No contacts added yet.', editMedicine: 'Edit medicine', medicineUpdated: 'Medicine updated.', medicineAdded: 'Medicine added to the schedule.', contactSaved: 'Contact saved.', medicineName: 'Medicine name', dosage: 'Dosage', timesComma: 'Time(s), comma separated', startDate: 'Start date', endDate: 'End date', colour: 'Colour', contactType: 'Contact type', doctor: 'Doctor', pharmacy: 'Pharmacy', specialty: 'Specialty', address: 'Address', save: 'Save', close: 'Close', cancel: 'Cancel',
  emergencyAction: 'Emergency action', requestEmergencyHelp: 'Request emergency help?', sosModalBody: 'We will alert connected caregivers and share your location if available.', sending: 'Sending…', sendEmergencySos: 'Send emergency SOS', sosSent: 'SOS sent to your caregivers.', patientLinked: 'Patient linked successfully.', joinPatient: 'Join a patient plan', joinPatientBody: 'Enter the invite code shared by the patient.', inviteCode: 'Invite code', joinNow: 'Join now', doseRecorded: 'Dose recorded. Well done!', doseSkipped: 'Dose marked as skipped.'
};

const hi = {
  ...en,
  brandTitle: 'स्वास्थ्य सहायता,', brandTitleAccent: 'घर के पास।', brandDescription: 'आपके लिए आसान दवा देखभाल। परिवार के लिए मन की शांति।', privacyNote: 'निजी, केवल परिवार के स्वास्थ्य अपडेट', pillVoice: 'आवाज़ से आसान', pillCare: 'परिवार जुड़ा', pillBilingual: 'English + हिन्दी',
  welcomeLabel: 'वापस स्वागत है', newAccountLabel: 'शुरू करें', welcomeBack: 'वापस स्वागत है', createAccount: 'खाता बनाएँ', signInSubtitle: 'अपने हेल्थ कम्पैनियन में साइन इन करें।', accountSubtitle: 'चुनें कि आप HealthMitra का उपयोग कैसे करेंगे।', chooseRole: 'भूमिका चुनें', patient: 'मरीज़', caregiver: 'देखभालकर्ता', name: 'आपका नाम', namePlaceholder: 'पूरा नाम', phone: 'फ़ोन नंबर', email: 'ईमेल पता', password: 'पासवर्ड', pleaseWait: 'कृपया प्रतीक्षा करें…', signIn: 'साइन इन', tryDemo: 'डेमो आज़माएँ', patientDemo: 'मरीज़: मीरा', caregiverDemo: 'देखभालकर्ता: अर्जुन', newToHealthMitra: 'HealthMitra में नए हैं?', alreadyAccount: 'पहले से खाता है?', prototypeNote: 'शैक्षणिक प्रोटोटाइप · केवल डेमो डेटा',
  patientMode: 'मरीज़ मोड', caregiverMode: 'देखभालकर्ता मोड', mainNavigation: 'मुख्य नेविगेशन', language: 'भाषा', logout: 'लॉग आउट', greeting: 'सुप्रभात', watching: 'देख रहे हैं', sos: 'आपातकालीन SOS', noLinkedPatients: 'अभी कोई मरीज़ लिंक नहीं है।', loadingPlan: 'आपका हेल्थ प्लान लोड हो रहा है…', joinWithCode: 'कोड से जुड़ें', dismiss: 'हटाएँ',
  voiceUnsupported: 'इस ब्राउज़र में आवाज़ पहचान उपलब्ध नहीं है।', voiceTryAgain: 'मैं सुन नहीं पाया। कृपया फिर प्रयास करें।', listening: 'सुन रहे हैं…', voiceUnclear: 'हाँ या नहीं समझ नहीं आया।', today: 'आज की दवाइयाँ', medications: 'दवाइयाँ', symptoms: 'लक्षण', contacts: 'संपर्क', dashboard: 'डैशबोर्ड', history: 'इतिहास', alerts: 'सूचनाएँ', patientToday: 'आपकी दिनचर्या', reassurance: 'आप बहुत अच्छा कर रहे हैं। एक कदम एक समय पर।', allCaughtUp: 'आज की सभी दवाएँ पूरी!', dosesComplete: '{{total}} में से {{taken}} खुराक पूरी', tapAfterTaking: 'दवा लेने के बाद उस पर टैप करें।', complete: 'पूरा', missedDoseTitle: 'एक खुराक पर ध्यान दें', missedDoseBody: 'देखभालकर्ता को सूचित कर दिया गया है।', noMeds: 'कोई दवा निर्धारित नहीं है', needHelp: 'तुरंत मदद चाहिए?', sosDescription: 'देखभालकर्ताओं को सूचना और स्थान भेजें।', addMedicine: 'दवा जोड़ें', keepScheduleCurrent: 'समय-सारणी अपडेट रखें।', consistencyTipTitle: 'नियमितता से बहुत मदद मिलती है।', consistencyTipBody: 'हर दिन एक ही समय पर दवा लेना अच्छी आदत बनाने में मदद करता है।', medication: 'दवा', sayIt: 'बोलें', taken: 'ले ली', skipped: 'छोड़ दी', missed: 'छूट गई', pending: 'बाकी', voice: 'आवाज़',
  caregiverView: 'देखभालकर्ता दृश्य', dashboardSubtitle: 'आपके प्रियजन की दिनचर्या का साफ़ और शांत दृश्य।', linkedPatients: 'लिंक किए गए मरीज़', selectPatient: 'प्लान देखने के लिए मरीज़ चुनें।', todayAdherence: 'आज का पालन', yourLovedOne: 'आपके प्रियजन', needsAttention: 'ध्यान चाहिए', doingWell: 'आज सब अच्छा है', dayStreak: 'दिन की लड़ी', todaysAdherence: 'आज का पालन', dosesTaken: 'ली गई खुराक', openAlerts: 'खुली सूचनाएँ', weeklyAdherence: 'साप्ताहिक पालन', weeklySubtitle: 'पिछले 7 दिनों का सरल दृश्य।', todaysSchedule: 'आज की समय-सारणी', liveSchedule: 'मरीज़ प्लान की ताज़ा स्थिति।',
  medicineSchedule: 'दवा समय-सारणी', scheduleSubtitle: 'हर प्रिस्क्रिप्शन को एक सरल जगह रखें।', timesDaily: 'बार रोज़ाना', ongoing: 'जारी', readOnlySchedule: 'इस समय-सारणी के लिए आपके पास केवल देखने की अनुमति है।', edit: 'बदलें', remove: 'हटाएँ', removeMedicineConfirm: '{{name}} को समय-सारणी से हटाएँ?', medicineRemoved: 'दवा हटा दी गई।', noHistory: 'अभी कोई इतिहास नहीं है।', medicationHistory: 'दवा इतिहास', historySubtitle: '{{name}} की हाल की खुराक प्रतिक्रियाएँ।',
  careUpdates: 'देखभाल अपडेट', alertsSubtitle: 'दवा और आपातकालीन घटनाएँ।', emergencySos: 'आपातकालीन SOS', healthMitra: 'HealthMitra', markRead: 'पढ़ा हुआ', noAlerts: 'कोई सूचना नहीं है।', sosHistory: 'SOS इतिहास', sosHistorySubtitle: 'आपातकालीन घटनाओं की समीक्षा करें और उन्हें बंद करें।', locationShared: 'स्थान साझा', locationUnavailable: 'स्थान उपलब्ध नहीं', openMap: 'मानचित्र खोलें', acknowledge: 'स्वीकार करें', resolve: 'समाधान करें', sosUpdated: 'SOS स्थिति अपडेट हुई।', noSos: 'कोई SOS घटना दर्ज नहीं है।', active: 'सक्रिय', acknowledged: 'स्वीकार किया', resolved: 'समाधान हुआ',
  patientTool: 'मरीज़ टूल', feelingQuestion: 'आप कैसा महसूस कर रहे हैं?', symptomSubtitle: 'केवल हल्के सामान्य लक्षणों के लिए। यह निदान नहीं है।', selectSymptom: 'लक्षण चुनें', speak: 'बोलें', severeCheck: 'लक्षण गंभीर, अचानक या बढ़ रहे हैं', safeGuidance: 'सुरक्षित जानकारी देखें', gentleSuggestion: 'हल्की स्व-देखभाल सलाह', seekMedicalGuidance: 'कृपया डॉक्टर से सलाह लें', safetyFirst: 'सुरक्षा पहले', persistentDisclaimer: 'यह चिकित्सा सलाह नहीं है। लक्षण बने रहें या बढ़ें तो डॉक्टर से सलाह लें।', symptomHeard: 'मैंने {{symptom}} सुना।', symptomUnclear: 'सूची से लक्षण चुनें या फिर बोलकर प्रयास करें।', headache: 'सिरदर्द', 'mild fever': 'हल्का बुखार', 'common cold': 'सामान्य सर्दी', 'mild body ache': 'हल्का बदन दर्द', 'mild cough': 'हल्की खाँसी',
  helpfulContacts: 'उपयोगी संपर्क', contactsSubtitle: 'आपके परिवार के भरोसेमंद डॉक्टर और फ़ार्मेसी।', linkCaregiver: 'देखभालकर्ता जोड़ें', linkCaregiverTitle: 'देखभालकर्ता लिंक करें', linkCaregiverBody: 'मौजूदा देखभालकर्ता खाते का ईमेल दर्ज करें। आप केवल देखने या समय-सारणी बदलने की अनुमति चुन सकते हैं।', caregiverEmail: 'देखभालकर्ता ईमेल', permission: 'अनुमति', viewOnly: 'केवल देखें', canEdit: 'समय-सारणी बदल सकते हैं', caregiverLinked: 'देखभालकर्ता लिंक हो गया।', inviteCodeLabel: 'आमंत्रण कोड', addContact: 'संपर्क जोड़ें', doctors: 'डॉक्टर', pharmacies: 'फ़ार्मेसी', detailsNotAdded: 'विवरण नहीं जोड़ा गया', noContacts: 'अभी कोई संपर्क नहीं जोड़ा गया।', editMedicine: 'दवा बदलें', medicineUpdated: 'दवा अपडेट हुई।', medicineAdded: 'दवा समय-सारणी में जोड़ी गई।', contactSaved: 'संपर्क सहेजा गया।', medicineName: 'दवा का नाम', dosage: 'खुराक', timesComma: 'समय, कॉमा से अलग', startDate: 'शुरू होने की तारीख', endDate: 'समाप्ति तारीख', colour: 'रंग', contactType: 'संपर्क प्रकार', doctor: 'डॉक्टर', pharmacy: 'फ़ार्मेसी', specialty: 'विशेषज्ञता', address: 'पता', save: 'सहेजें', close: 'बंद करें', cancel: 'रद्द करें',
  emergencyAction: 'आपातकालीन कार्रवाई', requestEmergencyHelp: 'आपातकालीन मदद माँगें?', sosModalBody: 'हम जुड़े देखभालकर्ताओं को सूचित करेंगे और उपलब्ध होने पर आपका स्थान साझा करेंगे।', sending: 'भेज रहे हैं…', sendEmergencySos: 'आपातकालीन SOS भेजें', sosSent: 'आपके देखभालकर्ताओं को SOS भेज दिया गया।', patientLinked: 'मरीज़ सफलतापूर्वक लिंक हुआ।', joinPatient: 'मरीज़ प्लान से जुड़ें', joinPatientBody: 'मरीज़ द्वारा साझा किया गया आमंत्रण कोड दर्ज करें।', inviteCode: 'आमंत्रण कोड', joinNow: 'अभी जुड़ें', doseRecorded: 'खुराक दर्ज हुई। बहुत अच्छा!', doseSkipped: 'खुराक छोड़ दी गई।'
};

i18n.use(initReactI18next).init({ resources: { en: { translation: en }, hi: { translation: hi } }, lng: 'en', fallbackLng: 'en', interpolation: { escapeValue: false }, returnNull: false });

export default i18n;
